- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: ./docker-compose.yml
  tags: app

- name: Start the app
  community.docker.docker_compose_v2:
    project_src: .
    state: present
  tags: app

- name: Wipe the app
  import_tasks: wipe.yml
  tags: wipe-web-app
  when: wipe_web_app == true
