- name: Remove the app container
  community.docker.docker_compose_v2:
    project_src: "{{ app_directory }}"
    state: absent
    remove_images: all
    remove_volumes: true
- name: Remove the directory
  ansible.builtin.file:
    path: "{{ app_directory }}/"
    state: absent
