networks:
  loki:

volumes:
  prometheus-data:
  grafana-data:

services:
  web_app:
    build: ../app_python
    volumes:
      - ./python-data:/app/data
    ports:
      - "8080:8080"
    networks:
      - loki
    mem_limit: 30m
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]

  web_app_haskell:
    build: ../app_haskell
    ports:
      - "8081:8081"
    networks:
      - loki
    mem_limit: 30m
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/localhost/8081'"]

  loki:
    image: grafana/loki:2.9.2
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    mem_limit: 100m
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/ready"]

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /home/snejugal/.local/share/docker/containers:/var/lib/docker/containers
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    mem_limit: 100m
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/localhost/9080'"]

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana.yml:/etc/grafana/provisioning/datasources/ds.yaml
    mem_limit: 100m
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - loki
    mem_limit: 100m
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
