apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-deployment
spec:
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: snejugal/devops-lab2
        ports:
        - containerPort: 8080
