apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-haskell-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: haskell.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-haskell-service
            port:
              number: 8081
