name: Haskell web application

on:
  push:
    paths:
      - "app_haskell/**/*"

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.2.8"
          enable-stack: true
          stack-version: "latest"
      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-haskell
        with:
          path: |
            ~/.cabal
            ~/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app_haskell/stack.yaml*') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run tests
        run: |
          cd app_haskell
          stack test
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: app_haskell/
        file: app_haskell/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-lab2-haskell:latest
