name: Python web application

on:
  push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.2"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r app_python/requirements.txt
    - name: Lint with flake8
      run: |
        flake8 app_python/src/
    - name: Test with pytest
      run: |
        pytest app_python/src/test.py
